#!/usr/bin/env bash
#Run Nginx as Nginx
sudo chmod -R 755 /etc/nginx/
sudo pkill -9 apache2
sudo sed -i 's/8080/8081/g' /etc/apache2/ports.conf
sudo service apache2 restart
sudo nginx -c "sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default"
sudo nginx service restart
