#!/usr/bin/env bash
#Run Nginx as Nginx
sudo sed -i 's/user www-data/user nginx' /etc/nginx/nginx.config
sudo sed -i 's/80/8080/g' /etx/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.config
sudo -u nginx service nginx restart
