#!/usr/bin/env bash
# install load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy//haproxy.cfg

echo "
frontend cryptotechcode
    bind *:80
    mode http
    default_backend app

backend app
    balance roundrobin
    server 6362-web-01 54.224.252.175:80 check
    server 6362-web-02 54.175.30.67 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
